version: "3"

services:
  rng:
    image: billmills/dockercoins_rng
    networks:
    - dockercoins
    ports:
    - "8001:80"

  hasher:
    image: billmills/dockercoins_hasher
    networks:
    - dockercoins
    ports:
    - "8002:80"

  webui:
    image: billmills/dockercoins_webui
    networks:
    - dockercoins
    ports:
    - "8000:80"
    volumes:
    - "./webui/files/:/files/"

  redis:
    image: redis
    networks:
    - dockercoins

  worker:
    image: billmills/dockercoins_worker
    networks:
    - dockercoins

networks:
    dockercoins:
