version: "3"

services:
  rng:
    image: user/dockercoins_rng
    networks:
    - dockercoins
    ports:
    - "8001:80"

  hasher:
    image: user/dockercoins_hasher
    networks:
    - dockercoins
    ports:
    - "8002:80"

  webui:
    image: user/dockercoins_webui
    networks:
    - dockercoins
    ports:
    - "8000:80"

  redis:
    image: redis
    networks:
    - dockercoins

  worker:
    image: user/dockercoins_worker
    networks:
    - dockercoins

networks:
    dockercoins:
